const vscode = require('vscode');
const { Configuration, OpenAIApi } = require('openai');
const { encode } = require('gpt-3-encoder');

const config = vscode.workspace.getConfiguration('codedoc');

const configuration = new Configuration({
	apiKey: config.get('api_key'),
});

const openai = new OpenAIApi(configuration);
const clamp = (num, min, max) => Math.min(Math.max(num, min), max); // From some stack overflow article from a while ago

const MAX_TOKENS = 2048;

// All of this documentation was generated by CodeDoc

/**
 * @function getOpenAIChoice
 * @param {object} response 
 * @returns {string}
 */
function getOpenAIChoice(response) {
	// Get the choices from the response
	const choices = response.data.choices;
	
	// If there are choices, return the first one
	if (choices && choices.length > 0) 
		return choices[0].text.replace('', '').replace('undefined').trim();
}

/**
 * @async
 * @function generateDocumentationHeader
 * @param {string} code - The code to generate a jsdoc header for.
 * @returns {Promise.<string>} - A promise containing the generated jsdoc header.
 */
async function generateDocumentationHeader(code) {
	const maxTokens = config.get('max_tokens');

    return await openai.createCompletion('text-davinci-002', {
		prompt: `Create a jsdoc header for the following code:\n${code}`,
		temperature: 0.7,
		max_tokens: clamp(MAX_TOKENS - encode(code).length, 1, maxTokens),
		top_p: 1,
		frequency_penalty: 0,
		presence_penalty: 0
	});
}

/**
 * @async
 * @function generateDocumentation
 * @param {string} code - The code to generate documentation for
 * @returns {Promise} - The documentation for the code
 * 
 * This function uses the openai API to generate documentation for
 * complicated lines of code.
 */
async function generateDocumentation(code) {
	return await openai.createEdit('code-davinci-edit-001', {
		input: code,
		instruction: 'Document any complicated lines of this code',
		temperature: 0,
		top_p: 1
	});
}

module.exports = { generateDocumentationHeader, generateDocumentation, getOpenAIChoice };